[package]
name = "counter"
version = "0.1.0"
authors = ["Myridia <info@myrida.com>"]
edition = "2024"
publish = false

[dependencies]
iced = { version = "0.13.1", features = ["debug"] }
#iced_native = "0.5.0"
#env_logger = "0.9"

#[build]
#incremental = true